name: deploy

on:
  push:
    branches:
      - trader37

jobs:
  on-success:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy trader37
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        continue-on-error: true
        env:
          TARGET_DIR: /home/trader37
          VENV_BIN: venv/bin
        with:
          host: ${{ secrets.PROD_HOST_BIG }}
          user: trader37
          pass: ${{ secrets.PROD_PASSWORD_BIG }}
          port: 22
          connect_timeout: 10s
          first_ssh: |-
            mkdir -p app
            mkdir -p logs
            test -d venv || python3.11 -m venv venv

          scp: |-
            './app/*' => $TARGET_DIR/app/
            './etc/*' => $TARGET_DIR/etc/
            ./requirements.txt => $TARGET_DIR

          last_ssh: |-
            $VENV_BIN/pip install pip setuptools --upgrade
            $VENV_BIN/pip install -r requirements.txt
            $VENV_BIN/pip cache purge
            mv etc/env .env
            chown :www-data .
            chmod 771 .
            chown -R :www-data ./etc
            chmod -R 760 ./etc
            chown :www-data .env 
            chmod 760 .env
            echo '' >> .env
            echo 'binance_api_key=${{ secrets.BINANCE_API_KEY }}' >> .env
            echo 'binance_api_secret=${{ secrets.BINANCE_API_SECRET }}' >> .env
            supervisorctl restart trader37
