name: deploy-pool-3

on:
  push:
    branches:
      - release-pool-3

jobs:
  on-success:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bot-name:
          - 'trader101'
          - 'trader102'
          - 'trader103'
          - 'trader104'
          - 'trader105'
          - 'trader106'
          - 'trader107'
          - 'trader108'
          - 'trader109'
          - 'trader110'
          - 'trader112'
          - 'trader113'
          - 'trader114'
          - 'trader115'
          - 'trader116'
          - 'trader117'
          - 'trader118'
          - 'trader119'
          - 'trader120'
          - 'trader121'
          - 'trader122'
          - 'trader123'
          - 'trader124'
          - 'trader125'
          - 'trader126'
          - 'trader127'
          - 'trader128'
          - 'trader129'
          - 'trader130'
          - 'trader131'
          - 'trader132'
          - 'trader133'
          - 'trader134'
          - 'trader135'
          - 'trader136'
          - 'trader137'
          - 'trader138'
          - 'trader139'

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy ${{ matrix.bot-name }}
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        continue-on-error: true
        env:
          TARGET_DIR: /home/${{ matrix.bot-name }}
          VENV_BIN: venv/bin
        with:
          host: ${{ secrets.PROD_HOST_BIG }}
          user: ${{ matrix.bot-name }}
          pass: ${{ secrets.PROD_PASSWORD_BIG }}
          port: 22
          connect_timeout: 10s
          first_ssh: |-
            mkdir -p app
            mkdir -p logs
            mkdir -p etc
            test -d venv || python3.11 -m venv venv

          scp: |-
            './app/*' => $TARGET_DIR/app/
            ./requirements.txt => $TARGET_DIR

          last_ssh: |-
            $VENV_BIN/pip install pip setuptools --upgrade
            $VENV_BIN/pip install -r requirements.txt
            $VENV_BIN/pip cache purge
            chown :www-data .
            chmod 771 .
            chown -R :www-data ./etc
            chmod -R 760 ./etc
            chown :www-data .env 
            chmod 760 .env
            supervisorctl restart ${{ matrix.bot-name }}
