name: deploy

on:
  push:
    branches:
      - USER_NAME

jobs:
  on-success:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy USER_NAME
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        continue-on-error: true
        env:
          TARGET_DIR: /home/USER_NAME
          VENV_BIN: venv/bin
        with:
          host: ${{ secrets.PROD_HOST }}
          user: USER_NAME
          pass: ${{ secrets.PROD_PASSWORD }}
          port: 22
          connect_timeout: 10s
          first_ssh: |-
            mkdir -p app
            mkdir -p logs
            test -d venv || python3.11 -m venv venv

          scp: |-
            './app/*' => $TARGET_DIR/app/
            ./etc/env => $TARGET_DIR/.env
            ./requirements.txt => $TARGET_DIR

          last_ssh: |-
            $VENV_BIN/pip install pip setuptools --upgrade
            $VENV_BIN/pip install -r requirements.txt
            $VENV_BIN/pip cache purge
            echo '' >> .env
            echo 'binance_api_key=${{ secrets.BINANCE_API_KEY }}' >> .env
            echo 'binance_api_secret=${{ secrets.BINANCE_API_SECRET }}' >> .env
            supervisorctl restart USER_NAME
