name: rebase-pool-1

on:
  push:
    branches: [master]

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v2
        with:
          base: master
          token: ${{ secrets.PAT }}
          include-labels: |
            rebase
